export const ColorSchemeValues = [
  'primary',
  'secondary',
  'accent',
  'muted',
] as const;

export const ColorValues = [
  ...ColorSchemeValues,
  'supernova',
  'supernova-dark',
  'nebula-blue-shades',
  'nebula-blue',
  'nebula-blue-dark',
  'cobalt-dark',
  'alert-medium',
  'cobalt',
  'comet',
  'comet-dark',
  'additional-link',
  'success-dark',
  'success-light',
  'error-light',
  'error',
  'error-dark',
  'alert-light',
  'alert-dark',
  'info-light',
  'info-dark',
  'inherit',
  'darkest',
  'darker',
  'neutral',
  'disabled-light',
  'light',
  'lighter',
  'white',
  'grey-1',
  'grey-2',
  'grey-3',
  'grey-4',
  'primary',
] as const;
