/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Variant } from "./common/types/variants";
import { ColorScheme } from "./common/types/color-scheme";
import { Size } from "./common/types/size";
export { Variant } from "./common/types/variants";
export { ColorScheme } from "./common/types/color-scheme";
export { Size } from "./common/types/size";
export namespace Components {
    interface SolarisButton {
        "color": ColorScheme;
        "fullWidth": boolean;
        "href": string;
        "iconSize": Size;
        "radius": number;
        "size": Size;
        "styling": string;
        "variant": Variant;
    }
    interface SolarisIcon {
    }
    interface SolarisSwitch {
    }
    interface SolarisThemeProvider {
        "theme": SolarisThemeProps;
    }
}
declare global {
    interface HTMLSolarisButtonElement extends Components.SolarisButton, HTMLStencilElement {
    }
    var HTMLSolarisButtonElement: {
        prototype: HTMLSolarisButtonElement;
        new (): HTMLSolarisButtonElement;
    };
    interface HTMLSolarisIconElement extends Components.SolarisIcon, HTMLStencilElement {
    }
    var HTMLSolarisIconElement: {
        prototype: HTMLSolarisIconElement;
        new (): HTMLSolarisIconElement;
    };
    interface HTMLSolarisSwitchElement extends Components.SolarisSwitch, HTMLStencilElement {
    }
    var HTMLSolarisSwitchElement: {
        prototype: HTMLSolarisSwitchElement;
        new (): HTMLSolarisSwitchElement;
    };
    interface HTMLSolarisThemeProviderElement extends Components.SolarisThemeProvider, HTMLStencilElement {
    }
    var HTMLSolarisThemeProviderElement: {
        prototype: HTMLSolarisThemeProviderElement;
        new (): HTMLSolarisThemeProviderElement;
    };
    interface HTMLElementTagNameMap {
        "solaris-button": HTMLSolarisButtonElement;
        "solaris-icon": HTMLSolarisIconElement;
        "solaris-switch": HTMLSolarisSwitchElement;
        "solaris-theme-provider": HTMLSolarisThemeProviderElement;
    }
}
declare namespace LocalJSX {
    interface SolarisButton {
        "color"?: ColorScheme;
        "fullWidth"?: boolean;
        "href"?: string;
        "iconSize"?: Size;
        "radius"?: number;
        "size"?: Size;
        "styling"?: string;
        "variant"?: Variant;
    }
    interface SolarisIcon {
    }
    interface SolarisSwitch {
    }
    interface SolarisThemeProvider {
        "theme"?: SolarisThemeProps;
    }
    interface IntrinsicElements {
        "solaris-button": SolarisButton;
        "solaris-icon": SolarisIcon;
        "solaris-switch": SolarisSwitch;
        "solaris-theme-provider": SolarisThemeProvider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "solaris-button": LocalJSX.SolarisButton & JSXBase.HTMLAttributes<HTMLSolarisButtonElement>;
            "solaris-icon": LocalJSX.SolarisIcon & JSXBase.HTMLAttributes<HTMLSolarisIconElement>;
            "solaris-switch": LocalJSX.SolarisSwitch & JSXBase.HTMLAttributes<HTMLSolarisSwitchElement>;
            "solaris-theme-provider": LocalJSX.SolarisThemeProvider & JSXBase.HTMLAttributes<HTMLSolarisThemeProviderElement>;
        }
    }
}
