/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Color, ColorScheme } from "./common/types/color-scheme";
import { IconName } from "./common/types/icon";
export { Color, ColorScheme } from "./common/types/color-scheme";
export { IconName } from "./common/types/icon";
export namespace Components {
    interface SolarisAccordion {
    }
    interface SolarisAvatar {
        "backgroundColor"?: ColorScheme;
    }
    interface SolarisButton {
        "color": 'supernova' | 'error' | 'nebula-blue' | 'myrtille' | 'black' | 'disabled-light' | 'neutral' | 'comet';
        "customClass"?: string;
        "disabled": boolean;
        "focusable"?: boolean;
        "href"?: string;
        "icon"?: IconName;
        "iconPosition": 'left' | 'right';
        "loading"?: boolean;
        "radius"?: number;
        "size": 'sm' | 'md' | 'lg';
        "type": 'default' | 'outline' | 'link';
    }
    interface SolarisIcon {
        "name": IconName;
        "variant": 'regular' | 'bold' | 'light';
    }
    interface SolarisModal {
    }
    interface SolarisSwitch {
        "checked": boolean;
        "disabled": boolean;
    }
    interface SolarisThemeProvider {
        "theme": Partial<{
    presets: 'PART' | 'PRO';
    colors: Partial<{
      primary: Color;
      secondary: Color;
      accent: Color;
    }>;
  }>;
    }
}
declare global {
    interface HTMLSolarisAccordionElement extends Components.SolarisAccordion, HTMLStencilElement {
    }
    var HTMLSolarisAccordionElement: {
        prototype: HTMLSolarisAccordionElement;
        new (): HTMLSolarisAccordionElement;
    };
    interface HTMLSolarisAvatarElement extends Components.SolarisAvatar, HTMLStencilElement {
    }
    var HTMLSolarisAvatarElement: {
        prototype: HTMLSolarisAvatarElement;
        new (): HTMLSolarisAvatarElement;
    };
    interface HTMLSolarisButtonElement extends Components.SolarisButton, HTMLStencilElement {
    }
    var HTMLSolarisButtonElement: {
        prototype: HTMLSolarisButtonElement;
        new (): HTMLSolarisButtonElement;
    };
    interface HTMLSolarisIconElement extends Components.SolarisIcon, HTMLStencilElement {
    }
    var HTMLSolarisIconElement: {
        prototype: HTMLSolarisIconElement;
        new (): HTMLSolarisIconElement;
    };
    interface HTMLSolarisModalElement extends Components.SolarisModal, HTMLStencilElement {
    }
    var HTMLSolarisModalElement: {
        prototype: HTMLSolarisModalElement;
        new (): HTMLSolarisModalElement;
    };
    interface HTMLSolarisSwitchElement extends Components.SolarisSwitch, HTMLStencilElement {
    }
    var HTMLSolarisSwitchElement: {
        prototype: HTMLSolarisSwitchElement;
        new (): HTMLSolarisSwitchElement;
    };
    interface HTMLSolarisThemeProviderElement extends Components.SolarisThemeProvider, HTMLStencilElement {
    }
    var HTMLSolarisThemeProviderElement: {
        prototype: HTMLSolarisThemeProviderElement;
        new (): HTMLSolarisThemeProviderElement;
    };
    interface HTMLElementTagNameMap {
        "solaris-accordion": HTMLSolarisAccordionElement;
        "solaris-avatar": HTMLSolarisAvatarElement;
        "solaris-button": HTMLSolarisButtonElement;
        "solaris-icon": HTMLSolarisIconElement;
        "solaris-modal": HTMLSolarisModalElement;
        "solaris-switch": HTMLSolarisSwitchElement;
        "solaris-theme-provider": HTMLSolarisThemeProviderElement;
    }
}
declare namespace LocalJSX {
    interface SolarisAccordion {
    }
    interface SolarisAvatar {
        "backgroundColor"?: ColorScheme;
    }
    interface SolarisButton {
        "color"?: 'supernova' | 'error' | 'nebula-blue' | 'myrtille' | 'black' | 'disabled-light' | 'neutral' | 'comet';
        "customClass"?: string;
        "disabled"?: boolean;
        "focusable"?: boolean;
        "href"?: string;
        "icon"?: IconName;
        "iconPosition"?: 'left' | 'right';
        "loading"?: boolean;
        "radius"?: number;
        "size"?: 'sm' | 'md' | 'lg';
        "type"?: 'default' | 'outline' | 'link';
    }
    interface SolarisIcon {
        "name"?: IconName;
        "variant"?: 'regular' | 'bold' | 'light';
    }
    interface SolarisModal {
    }
    interface SolarisSwitch {
        "checked"?: boolean;
        "disabled"?: boolean;
    }
    interface SolarisThemeProvider {
        "theme"?: Partial<{
    presets: 'PART' | 'PRO';
    colors: Partial<{
      primary: Color;
      secondary: Color;
      accent: Color;
    }>;
  }>;
    }
    interface IntrinsicElements {
        "solaris-accordion": SolarisAccordion;
        "solaris-avatar": SolarisAvatar;
        "solaris-button": SolarisButton;
        "solaris-icon": SolarisIcon;
        "solaris-modal": SolarisModal;
        "solaris-switch": SolarisSwitch;
        "solaris-theme-provider": SolarisThemeProvider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "solaris-accordion": LocalJSX.SolarisAccordion & JSXBase.HTMLAttributes<HTMLSolarisAccordionElement>;
            "solaris-avatar": LocalJSX.SolarisAvatar & JSXBase.HTMLAttributes<HTMLSolarisAvatarElement>;
            "solaris-button": LocalJSX.SolarisButton & JSXBase.HTMLAttributes<HTMLSolarisButtonElement>;
            "solaris-icon": LocalJSX.SolarisIcon & JSXBase.HTMLAttributes<HTMLSolarisIconElement>;
            "solaris-modal": LocalJSX.SolarisModal & JSXBase.HTMLAttributes<HTMLSolarisModalElement>;
            "solaris-switch": LocalJSX.SolarisSwitch & JSXBase.HTMLAttributes<HTMLSolarisSwitchElement>;
            "solaris-theme-provider": LocalJSX.SolarisThemeProvider & JSXBase.HTMLAttributes<HTMLSolarisThemeProviderElement>;
        }
    }
}
